name: exoplayer_bindings
description: JNI bindings for ExoPlayer.
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jni: ^0.12.0

dev_dependencies:
  archive: ^4.0.7
  jnigen: ^0.12.0
  lints: ^3.0.0
  test: ^1.24.0
